port 26379

# 컨테이너 호스트명(redis-master)으로 마스터를 지정하기 위한 설정
sentinel resolve-hostnames yes
sentinel announce-hostnames yes

# <name> <host> <port> <quorum>  (Sentinel 1개라 quorum=1)
sentinel monitor mymaster redis-master 6379 1
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1
